version: '3.7'

services:

  client:
    container_name: client
    build:
      context: ./residentes-client/
      dockerfile: Dockerfile
    volumes:
      - './residentes-client/:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true